//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Users.
        /// </summary>
        public static string ActiveUsers {
            get {
                return ResourceManager.GetString("ActiveUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum requirements Android 4.0+.
        /// </summary>
        public static string AndroidReq {
            get {
                return ResourceManager.GetString("AndroidReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothes tagged.
        /// </summary>
        public static string ClothesTagged {
            get {
                return ResourceManager.GetString("ClothesTagged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloth It is a social network that targets fashion and trends about how to get dressed. Our goal is to bring users a different way to search for clothes or allowing them to get opinions from the community about the way they dress.
        /// </summary>
        public static string ClothitDesc {
            get {
                return ResourceManager.GetString("ClothitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string Copyrights {
            get {
                return ResourceManager.GetString("Copyrights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacho is the developer who works under the hood, his work is to make everything work.
        /// </summary>
        public static string FullStackDesc {
            get {
                return ResourceManager.GetString("FullStackDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Stack Developer.
        /// </summary>
        public static string FullStackTitle {
            get {
                return ResourceManager.GetString("FullStackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Goals.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Use.
        /// </summary>
        public static string Howto {
            get {
                return ResourceManager.GetString("Howto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a Pic.
        /// </summary>
        public static string HowToStep1 {
            get {
                return ResourceManager.GetString("HowToStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take yourself a picture and select and identify the pieces of clothing that you want to have some feedback.
        /// </summary>
        public static string HowToStep1Desc {
            get {
                return ResourceManager.GetString("HowToStep1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string HowToStep2 {
            get {
                return ResourceManager.GetString("HowToStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the way you dress in trending threads or in private groups with your friends.
        /// </summary>
        public static string HowToStep2Desc {
            get {
                return ResourceManager.GetString("HowToStep2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Feedback.
        /// </summary>
        public static string HowToStep3 {
            get {
                return ResourceManager.GetString("HowToStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the opinion from members of the community where you share your clothes, they could suggest you new clothes or combinations.
        /// </summary>
        public static string HowToStep3Desc {
            get {
                return ResourceManager.GetString("HowToStep3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be Popular.
        /// </summary>
        public static string HowToStep4 {
            get {
                return ResourceManager.GetString("HowToStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every time someone likes your clothes you will be more popular in your community, and your opinions will be more important.
        /// </summary>
        public static string HowToStep4Desc {
            get {
                return ResourceManager.GetString("HowToStep4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum requirements iPhone 4, iOS 8.0+.
        /// </summary>
        public static string IosReq {
            get {
                return ResourceManager.GetString("IosReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageChooser {
            get {
                return ResourceManager.GetString("LanguageChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebastián is the one who works on every aspect of Cloth It, in charge of the hard work.
        /// </summary>
        public static string LeadDesc {
            get {
                return ResourceManager.GetString("LeadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Developer.
        /// </summary>
        public static string LeadTitle {
            get {
                return ResourceManager.GetString("LeadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mauricio is in charge of getting new contacts and promote the site.
        /// </summary>
        public static string MarketingDesc {
            get {
                return ResourceManager.GetString("MarketingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing Manager.
        /// </summary>
        public static string MarketingTitle {
            get {
                return ResourceManager.GetString("MarketingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our Team.
        /// </summary>
        public static string MeetTeam {
            get {
                return ResourceManager.GetString("MeetTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platforms.
        /// </summary>
        public static string Platforms {
            get {
                return ResourceManager.GetString("Platforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Date.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec 2015.
        /// </summary>
        public static string ReleaseDate1 {
            get {
                return ResourceManager.GetString("ReleaseDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request an invite !!!.
        /// </summary>
        public static string RequestInvite {
            get {
                return ResourceManager.GetString("RequestInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll get access to early release of our app and updates of what we are actually doing..
        /// </summary>
        public static string RequestInviteDesc {
            get {
                return ResourceManager.GetString("RequestInviteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *We will never share, rent, or sell your email address to anyone, ever..
        /// </summary>
        public static string RequestInviteWarning {
            get {
                return ResourceManager.GetString("RequestInviteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your store interested?.
        /// </summary>
        public static string StoreInterested {
            get {
                return ResourceManager.GetString("StoreInterested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloth It offers Store profiles for those stores that want to publish or share new products or trends in our network. Contact us filling the form in order to have more information about Store profiles.
        /// </summary>
        public static string StoreInterestedDesc {
            get {
                return ResourceManager.GetString("StoreInterestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Profiles.
        /// </summary>
        public static string StoreProfiles {
            get {
                return ResourceManager.GetString("StoreProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use our revolutionary fashion app.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are a group of students from the Universidad Católica del Uruguay, all of us are currently working in the Computer Science field.
        /// </summary>
        public static string TeamDesc {
            get {
                return ResourceManager.GetString("TeamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sebastián is in charge of creating nice and tidy views, so the users can have a great experience.
        /// </summary>
        public static string UIUXDesc {
            get {
                return ResourceManager.GetString("UIUXDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI/UX Designer.
        /// </summary>
        public static string UIUXTitle {
            get {
                return ResourceManager.GetString("UIUXTitle", resourceCulture);
            }
        }
    }
}
