//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothItWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Newsletter
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public System.DateTime FechaAlta { get; set; }
    }
}
